### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by pongketkorn111** [luca28pet/MultiServerCounter#2]
ErrorException: "Use of undefined constant JSON_THROW_ON_ERROR - assumed 'JSON_THROW_ON_ERROR' (this will throw an Error in a future version of PHP)" (EXCEPTION) in "plugins/MultiServerCounter_dev-1.phar/src/luca28pet/MultiServerCounter/UpdatePlayersTask" at line 19

**Comment by luca28pet** [comment]
Update your php version,  >= 7.3 required
